USE [WIWA_Questionnaires_DB];
GO
SET NOCOUNT ON;
GO
-- Data Migration Script generated by Antigravity

IF OBJECT_ID('tempdb..#Map_QuestionnaireIdentificatorTypes') IS NOT NULL DROP TABLE #Map_QuestionnaireIdentificatorTypes;
CREATE TABLE #Map_QuestionnaireIdentificatorTypes (OldID INT, NewID INT);
 
PRINT 'Migrating QuestionnaireIdentificatorTypes...';
MERGE INTO [QuestionnaireIdentificatorTypes] AS Target
USING (
    SELECT Source.[Name], Source.[QuestionnaireIdentificatorTypeID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[QuestionnaireIdentificatorTypes] Source

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([Name])
    VALUES (SourceData.[Name])
    OUTPUT SourceData.OldID_Source, Inserted.[QuestionnaireIdentificatorTypeID] INTO #Map_QuestionnaireIdentificatorTypes;
GO

IF OBJECT_ID('tempdb..#Map_QuestionnaireTypes') IS NOT NULL DROP TABLE #Map_QuestionnaireTypes;
CREATE TABLE #Map_QuestionnaireTypes (OldID INT, NewID INT);
 
PRINT 'Migrating QuestionnaireTypes...';
MERGE INTO [QuestionnaireTypes] AS Target
USING (
    SELECT Source.[Name], Source.[Code], Source.[QuestionnaireCategoryID], Source.[QuestionnaireTypeID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[QuestionnaireTypes] Source

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([Name], [Code], [QuestionnaireCategoryID])
    VALUES (SourceData.[Name], SourceData.[Code], SourceData.[QuestionnaireCategoryID])
    OUTPUT SourceData.OldID_Source, Inserted.[QuestionnaireTypeID] INTO #Map_QuestionnaireTypes;
GO

IF OBJECT_ID('tempdb..#Map_SpecificQuestionTypes') IS NOT NULL DROP TABLE #Map_SpecificQuestionTypes;
CREATE TABLE #Map_SpecificQuestionTypes (OldID INT, NewID INT);
 
PRINT 'Migrating SpecificQuestionTypes...';
MERGE INTO [SpecificQuestionTypes] AS Target
USING (
    SELECT Source.[Name], Source.[SpecificQuestionTypeID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[SpecificQuestionTypes] Source

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([Name])
    VALUES (SourceData.[Name])
    OUTPUT SourceData.OldID_Source, Inserted.[SpecificQuestionTypeID] INTO #Map_SpecificQuestionTypes;
GO

IF OBJECT_ID('tempdb..#Map_QuestionFormats') IS NOT NULL DROP TABLE #Map_QuestionFormats;
CREATE TABLE #Map_QuestionFormats (OldID INT, NewID INT);
 
PRINT 'Migrating QuestionFormats...';
MERGE INTO [QuestionFormats] AS Target
USING (
    SELECT Source.[Name], Source.[Code], Source.[Description], Source.[QuestionFormatID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[QuestionFormats] Source

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([Name], [Code], [Description])
    VALUES (SourceData.[Name], SourceData.[Code], SourceData.[Description])
    OUTPUT SourceData.OldID_Source, Inserted.[QuestionFormatID] INTO #Map_QuestionFormats;
GO

IF OBJECT_ID('tempdb..#Map_ComputeMethods') IS NOT NULL DROP TABLE #Map_ComputeMethods;
CREATE TABLE #Map_ComputeMethods (OldID INT, NewID INT);
 
PRINT 'Migrating ComputeMethods...';
MERGE INTO [ComputeMethods] AS Target
USING (
    SELECT Source.[Code], Source.[Name], Source.[Description], Source.[IsActive], Source.[ComputeMethodID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[ComputeMethods] Source

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([Code], [Name], [Description], [IsActive])
    VALUES (SourceData.[Code], SourceData.[Name], SourceData.[Description], SourceData.[IsActive])
    OUTPUT SourceData.OldID_Source, Inserted.[ComputeMethodID] INTO #Map_ComputeMethods;
GO

IF OBJECT_ID('tempdb..#Map_Ranks') IS NOT NULL DROP TABLE #Map_Ranks;
CREATE TABLE #Map_Ranks (OldID INT, NewID INT);
 
PRINT 'Migrating Ranks...';
MERGE INTO [Ranks] AS Target
USING (
    SELECT Source.[Rank], Source.[Description], Source.[StateID], Source.[RankID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[Ranks] Source

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([Rank], [Description], [StateID])
    VALUES (SourceData.[Rank], SourceData.[Description], SourceData.[StateID])
    OUTPUT SourceData.OldID_Source, Inserted.[RankID] INTO #Map_Ranks;
GO

IF OBJECT_ID('tempdb..#Map_RiskLevels') IS NOT NULL DROP TABLE #Map_RiskLevels;
CREATE TABLE #Map_RiskLevels (OldID INT, NewID INT);
 
PRINT 'Migrating RiskLevels...';
MERGE INTO [RiskLevels] AS Target
USING (
    SELECT Source.[RiskLevel], Source.[Description], Source.[StateID], Source.[RiskLevelID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[RiskLevels] Source

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([RiskLevel], [Description], [StateID])
    VALUES (SourceData.[RiskLevel], SourceData.[Description], SourceData.[StateID])
    OUTPUT SourceData.OldID_Source, Inserted.[RiskLevelID] INTO #Map_RiskLevels;
GO

IF OBJECT_ID('tempdb..#Map_QuestionnaireIdentificators') IS NOT NULL DROP TABLE #Map_QuestionnaireIdentificators;
CREATE TABLE #Map_QuestionnaireIdentificators (OldID INT, NewID INT);
 
PRINT 'Migrating QuestionnaireIdentificators...';
MERGE INTO [QuestionnaireIdentificators] AS Target
USING (
    SELECT Map_QuestionnaireIdentificatorTypeID.NewID AS [QuestionnaireIdentificatorTypeID], Source.[Identificator], Source.[UserID], Source.[PoliticalPerson], Source.[QuestionnaireIdentificatorID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[QuestionnaireIdentificators] Source
 LEFT JOIN #Map_QuestionnaireIdentificatorTypes Map_QuestionnaireIdentificatorTypeID ON Source.[QuestionnaireIdentificatorTypeID] = Map_QuestionnaireIdentificatorTypeID.OldID

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([QuestionnaireIdentificatorTypeID], [Identificator], [UserID], [PoliticalPerson])
    VALUES (SourceData.[QuestionnaireIdentificatorTypeID], SourceData.[Identificator], SourceData.[UserID], SourceData.[PoliticalPerson])
    OUTPUT SourceData.OldID_Source, Inserted.[QuestionnaireIdentificatorID] INTO #Map_QuestionnaireIdentificators;
GO

IF OBJECT_ID('tempdb..#Map_Questions') IS NOT NULL DROP TABLE #Map_Questions;
CREATE TABLE #Map_Questions (OldID INT, NewID INT);
 
PRINT 'Migrating Questions...';
MERGE INTO [Questions] AS Target
USING (
    SELECT Source.[QuestionText], Source.[QuestionOrder], Map_QuestionFormatID.NewID AS [QuestionFormatID], Map_SpecificQuestionTypeID.NewID AS [SpecificQuestionTypeID], Source.[QuestionLabel], Source.[ParentQuestionID], Source.[ReadOnly], Source.[IsRequired], Source.[ValidationPattern], Source.[QuestionID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[Questions] Source
 LEFT JOIN #Map_QuestionFormats Map_QuestionFormatID ON Source.[QuestionFormatID] = Map_QuestionFormatID.OldID
 LEFT JOIN #Map_SpecificQuestionTypes Map_SpecificQuestionTypeID ON Source.[SpecificQuestionTypeID] = Map_SpecificQuestionTypeID.OldID

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([QuestionText], [QuestionOrder], [QuestionFormatID], [SpecificQuestionTypeID], [QuestionLabel], [ParentQuestionID], [ReadOnly], [IsRequired], [ValidationPattern])
    VALUES (SourceData.[QuestionText], SourceData.[QuestionOrder], SourceData.[QuestionFormatID], SourceData.[SpecificQuestionTypeID], SourceData.[QuestionLabel], SourceData.[ParentQuestionID], SourceData.[ReadOnly], SourceData.[IsRequired], SourceData.[ValidationPattern])
    OUTPUT SourceData.OldID_Source, Inserted.[QuestionID] INTO #Map_Questions;
GO

IF OBJECT_ID('tempdb..#Map_PredefinedAnswers') IS NOT NULL DROP TABLE #Map_PredefinedAnswers;
CREATE TABLE #Map_PredefinedAnswers (OldID INT, NewID INT);
 
PRINT 'Migrating PredefinedAnswers...';
MERGE INTO [PredefinedAnswers] AS Target
USING (
    SELECT Map_QuestionID.NewID AS [QuestionID], Source.[PreSelected], Source.[Answer], Source.[StatisticalWeight], Source.[Code], Source.[DisplayOrder], Source.[PredefinedAnswerID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[PredefinedAnswers] Source
 LEFT JOIN #Map_Questions Map_QuestionID ON Source.[QuestionID] = Map_QuestionID.OldID

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([QuestionID], [PreSelected], [Answer], [StatisticalWeight], [Code], [DisplayOrder])
    VALUES (SourceData.[QuestionID], SourceData.[PreSelected], SourceData.[Answer], SourceData.[StatisticalWeight], SourceData.[Code], SourceData.[DisplayOrder])
    OUTPUT SourceData.OldID_Source, Inserted.[PredefinedAnswerID] INTO #Map_PredefinedAnswers;
GO

IF OBJECT_ID('tempdb..#Map_PredefinedAnswerSubQuestions') IS NOT NULL DROP TABLE #Map_PredefinedAnswerSubQuestions;
CREATE TABLE #Map_PredefinedAnswerSubQuestions (OldID INT, NewID INT);
 
PRINT 'Migrating PredefinedAnswerSubQuestions...';
MERGE INTO [PredefinedAnswerSubQuestions] AS Target
USING (
    SELECT Map_PredefinedAnswerID.NewID AS [PredefinedAnswerID], Map_SubQuestionID.NewID AS [SubQuestionID], Source.[PredefinedAnswerSubQuestionID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[PredefinedAnswerSubQuestions] Source
 LEFT JOIN #Map_PredefinedAnswers Map_PredefinedAnswerID ON Source.[PredefinedAnswerID] = Map_PredefinedAnswerID.OldID
 LEFT JOIN #Map_Questions Map_SubQuestionID ON Source.[SubQuestionID] = Map_SubQuestionID.OldID

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([PredefinedAnswerID], [SubQuestionID])
    VALUES (SourceData.[PredefinedAnswerID], SourceData.[SubQuestionID])
    OUTPUT SourceData.OldID_Source, Inserted.[PredefinedAnswerSubQuestionID] INTO #Map_PredefinedAnswerSubQuestions;
GO

IF OBJECT_ID('tempdb..#Map_QuestionComputedConfigs') IS NOT NULL DROP TABLE #Map_QuestionComputedConfigs;
CREATE TABLE #Map_QuestionComputedConfigs (OldID INT, NewID INT);
 
PRINT 'Migrating QuestionComputedConfigs...';
MERGE INTO [QuestionComputedConfigs] AS Target
USING (
    SELECT Map_QuestionID.NewID AS [QuestionID], Map_ComputeMethodID.NewID AS [ComputeMethodID], Source.[MatrixObjectName], Source.[RuleName], Source.[RuleDescription], Source.[OutputMode], Source.[OutputTarget], Source.[MatrixOutputColumnName], Source.[Priority], Source.[IsActive], Source.[FormulaExpression], Source.[QuestionComputedConfigID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[QuestionComputedConfigs] Source
 LEFT JOIN #Map_Questions Map_QuestionID ON Source.[QuestionID] = Map_QuestionID.OldID
 LEFT JOIN #Map_ComputeMethods Map_ComputeMethodID ON Source.[ComputeMethodID] = Map_ComputeMethodID.OldID

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([QuestionID], [ComputeMethodID], [MatrixObjectName], [RuleName], [RuleDescription], [OutputMode], [OutputTarget], [MatrixOutputColumnName], [Priority], [IsActive], [FormulaExpression])
    VALUES (SourceData.[QuestionID], SourceData.[ComputeMethodID], SourceData.[MatrixObjectName], SourceData.[RuleName], SourceData.[RuleDescription], SourceData.[OutputMode], SourceData.[OutputTarget], SourceData.[MatrixOutputColumnName], SourceData.[Priority], SourceData.[IsActive], SourceData.[FormulaExpression])
    OUTPUT SourceData.OldID_Source, Inserted.[QuestionComputedConfigID] INTO #Map_QuestionComputedConfigs;
GO

IF OBJECT_ID('tempdb..#Map_Indicators') IS NOT NULL DROP TABLE #Map_Indicators;
CREATE TABLE #Map_Indicators (OldID INT, NewID INT);
 
PRINT 'Migrating Indicators...';
MERGE INTO [Indicators] AS Target
USING (
    SELECT Map_QuestionnaireIdentificatorID.NewID AS [QuestionnaireIdentificatorID], Map_RankID.NewID AS [RankID], Map_RiskLevelID.NewID AS [RiskLevelID], Source.[TransferDate], Source.[IndicatorID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[Indicators] Source
 LEFT JOIN #Map_QuestionnaireIdentificators Map_QuestionnaireIdentificatorID ON Source.[QuestionnaireIdentificatorID] = Map_QuestionnaireIdentificatorID.OldID
 LEFT JOIN #Map_Ranks Map_RankID ON Source.[RankID] = Map_RankID.OldID
 LEFT JOIN #Map_RiskLevels Map_RiskLevelID ON Source.[RiskLevelID] = Map_RiskLevelID.OldID

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([QuestionnaireIdentificatorID], [RankID], [RiskLevelID], [TransferDate])
    VALUES (SourceData.[QuestionnaireIdentificatorID], SourceData.[RankID], SourceData.[RiskLevelID], SourceData.[TransferDate])
    OUTPUT SourceData.OldID_Source, Inserted.[IndicatorID] INTO #Map_Indicators;
GO

IF OBJECT_ID('tempdb..#Map_QuestionnaireTypeRules') IS NOT NULL DROP TABLE #Map_QuestionnaireTypeRules;
CREATE TABLE #Map_QuestionnaireTypeRules (OldID INT, NewID INT);
 
PRINT 'Migrating QuestionnaireTypeRules...';
MERGE INTO [QuestionnaireTypeRules] AS Target
USING (
    SELECT Map_QuestionnaireTypeID.NewID AS [QuestionnaireTypeID], Source.[TotalStatisticalWeightFrom], Source.[TotalStatisticalWeightTo], Source.[FinalRate], Source.[ContractIssuingBlocker], Source.[Suitable], Source.[TariffID], Source.[QuestionnaireTypeRuleID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[QuestionnaireTypeRules] Source
 LEFT JOIN #Map_QuestionnaireTypes Map_QuestionnaireTypeID ON Source.[QuestionnaireTypeID] = Map_QuestionnaireTypeID.OldID

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([QuestionnaireTypeID], [TotalStatisticalWeightFrom], [TotalStatisticalWeightTo], [FinalRate], [ContractIssuingBlocker], [Suitable], [TariffID])
    VALUES (SourceData.[QuestionnaireTypeID], SourceData.[TotalStatisticalWeightFrom], SourceData.[TotalStatisticalWeightTo], SourceData.[FinalRate], SourceData.[ContractIssuingBlocker], SourceData.[Suitable], SourceData.[TariffID])
    OUTPUT SourceData.OldID_Source, Inserted.[QuestionnaireTypeRuleID] INTO #Map_QuestionnaireTypeRules;
GO

IF OBJECT_ID('tempdb..#Map_QuestionnaireTypeReferenceTables') IS NOT NULL DROP TABLE #Map_QuestionnaireTypeReferenceTables;
CREATE TABLE #Map_QuestionnaireTypeReferenceTables (OldID INT, NewID INT);
 
PRINT 'Migrating QuestionnaireTypeReferenceTables...';
MERGE INTO [QuestionnaireTypeReferenceTables] AS Target
USING (
    SELECT Map_QuestionnaireTypeID.NewID AS [QuestionnaireTypeID], Source.[TableName], Source.[QuestionnaireTypeReferenceTableID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[QuestionnaireTypeReferenceTables] Source
 LEFT JOIN #Map_QuestionnaireTypes Map_QuestionnaireTypeID ON Source.[QuestionnaireTypeID] = Map_QuestionnaireTypeID.OldID

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([QuestionnaireTypeID], [TableName])
    VALUES (SourceData.[QuestionnaireTypeID], SourceData.[TableName])
    OUTPUT SourceData.OldID_Source, Inserted.[QuestionnaireTypeReferenceTableID] INTO #Map_QuestionnaireTypeReferenceTables;
GO

IF OBJECT_ID('tempdb..#Map_QuestionReferenceColumns') IS NOT NULL DROP TABLE #Map_QuestionReferenceColumns;
CREATE TABLE #Map_QuestionReferenceColumns (OldID INT, NewID INT);
 
PRINT 'Migrating QuestionReferenceColumns...';
MERGE INTO [QuestionReferenceColumns] AS Target
USING (
    SELECT Source.[QuestionID], Map_QuestionnaireTypeReferenceTableID.NewID AS [QuestionnaireTypeReferenceTableID], Source.[ReferenceColumnName], Source.[QuestionReferenceColumnID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[QuestionReferenceColumns] Source
 LEFT JOIN #Map_QuestionnaireTypeReferenceTables Map_QuestionnaireTypeReferenceTableID ON Source.[QuestionnaireTypeReferenceTableID] = Map_QuestionnaireTypeReferenceTableID.OldID

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([QuestionID], [QuestionnaireTypeReferenceTableID], [ReferenceColumnName])
    VALUES (SourceData.[QuestionID], SourceData.[QuestionnaireTypeReferenceTableID], SourceData.[ReferenceColumnName])
    OUTPUT SourceData.OldID_Source, Inserted.[QuestionReferenceColumnID] INTO #Map_QuestionReferenceColumns;
GO

IF OBJECT_ID('tempdb..#Map_ProductQuestionaryTypes') IS NOT NULL DROP TABLE #Map_ProductQuestionaryTypes;
CREATE TABLE #Map_ProductQuestionaryTypes (OldID INT, NewID INT);
 
PRINT 'Migrating ProductQuestionaryTypes...';
MERGE INTO [ProductQuestionaryTypes] AS Target
USING (
    SELECT Source.[ProductID], Map_QuestionaryTypeID.NewID AS [QuestionaryTypeID], Source.[ProductQuestionaryTypeID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[ProductQuestionaryTypes] Source
 LEFT JOIN #Map_QuestionnaireTypes Map_QuestionaryTypeID ON Source.[QuestionaryTypeID] = Map_QuestionaryTypeID.OldID

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([ProductID], [QuestionaryTypeID])
    VALUES (SourceData.[ProductID], SourceData.[QuestionaryTypeID])
    OUTPUT SourceData.OldID_Source, Inserted.[ProductQuestionaryTypeID] INTO #Map_ProductQuestionaryTypes;
GO

IF OBJECT_ID('tempdb..#Map_QuestionnaireByQuestionnaireIdentificators') IS NOT NULL DROP TABLE #Map_QuestionnaireByQuestionnaireIdentificators;
CREATE TABLE #Map_QuestionnaireByQuestionnaireIdentificators (OldID INT, NewID INT);
 
PRINT 'Migrating QuestionnaireByQuestionnaireIdentificators...';
MERGE INTO [QuestionnaireByQuestionnaireIdentificators] AS Target
USING (
    SELECT Map_QuestionnaireIdentificatorID.NewID AS [QuestionnaireIdentificatorID], Map_QuestionnaireTypeID.NewID AS [QuestionnaireTypeID], Source.[StartDateTime], Source.[FinishDateTime], Source.[Locked], Source.[LastChange], Source.[QuestionnaireByQuestionnaireIdentificatorID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[QuestionnaireByQuestionnaireIdentificators] Source
 LEFT JOIN #Map_QuestionnaireIdentificators Map_QuestionnaireIdentificatorID ON Source.[QuestionnaireIdentificatorID] = Map_QuestionnaireIdentificatorID.OldID
 LEFT JOIN #Map_QuestionnaireTypes Map_QuestionnaireTypeID ON Source.[QuestionnaireTypeID] = Map_QuestionnaireTypeID.OldID

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([QuestionnaireIdentificatorID], [QuestionnaireTypeID], [StartDateTime], [FinishDateTime], [Locked], [LastChange])
    VALUES (SourceData.[QuestionnaireIdentificatorID], SourceData.[QuestionnaireTypeID], SourceData.[StartDateTime], SourceData.[FinishDateTime], SourceData.[Locked], SourceData.[LastChange])
    OUTPUT SourceData.OldID_Source, Inserted.[QuestionnaireByQuestionnaireIdentificatorID] INTO #Map_QuestionnaireByQuestionnaireIdentificators;
GO

IF OBJECT_ID('tempdb..#Map_Questionnaires') IS NOT NULL DROP TABLE #Map_Questionnaires;
CREATE TABLE #Map_Questionnaires (OldID INT, NewID INT);
 
PRINT 'Migrating Questionnaires...';
MERGE INTO [Questionnaires] AS Target
USING (
    SELECT Map_QuestionnaireTypeID.NewID AS [QuestionnaireTypeID], Map_QuestionID.NewID AS [QuestionID], Source.[QuestionnaireID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[Questionnaires] Source
 LEFT JOIN #Map_QuestionnaireTypes Map_QuestionnaireTypeID ON Source.[QuestionnaireTypeID] = Map_QuestionnaireTypeID.OldID
 LEFT JOIN #Map_Questions Map_QuestionID ON Source.[QuestionID] = Map_QuestionID.OldID

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([QuestionnaireTypeID], [QuestionID])
    VALUES (SourceData.[QuestionnaireTypeID], SourceData.[QuestionID])
    OUTPUT SourceData.OldID_Source, Inserted.[QuestionnaireID] INTO #Map_Questionnaires;
GO

IF OBJECT_ID('tempdb..#Map_QuestionnaireAnswers') IS NOT NULL DROP TABLE #Map_QuestionnaireAnswers;
CREATE TABLE #Map_QuestionnaireAnswers (OldID INT, NewID INT);
 
PRINT 'Migrating QuestionnaireAnswers...';
MERGE INTO [QuestionnaireAnswers] AS Target
USING (
    SELECT Map_QuestionID.NewID AS [QuestionID], Source.[Answer], Source.[AnswerPoints], Map_QuestionnaireByQuestionnaireIdentificatorID.NewID AS [QuestionnaireByQuestionnaireIdentificatorID], Map_PredefinedAnswerID.NewID AS [PredefinedAnswerID], Source.[QuestionnaireAnswerID] AS OldID_Source
    FROM [WIWA_DB_NEW].[dbo].[QuestionnaireAnswers] Source
 LEFT JOIN #Map_Questions Map_QuestionID ON Source.[QuestionID] = Map_QuestionID.OldID
 LEFT JOIN #Map_QuestionnaireByQuestionnaireIdentificators Map_QuestionnaireByQuestionnaireIdentificatorID ON Source.[QuestionnaireByQuestionnaireIdentificatorID] = Map_QuestionnaireByQuestionnaireIdentificatorID.OldID
 LEFT JOIN #Map_PredefinedAnswers Map_PredefinedAnswerID ON Source.[PredefinedAnswerID] = Map_PredefinedAnswerID.OldID

) AS SourceData
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT ([QuestionID], [Answer], [AnswerPoints], [QuestionnaireByQuestionnaireIdentificatorID], [PredefinedAnswerID])
    VALUES (SourceData.[QuestionID], SourceData.[Answer], SourceData.[AnswerPoints], SourceData.[QuestionnaireByQuestionnaireIdentificatorID], SourceData.[PredefinedAnswerID])
    OUTPUT SourceData.OldID_Source, Inserted.[QuestionnaireAnswerID] INTO #Map_QuestionnaireAnswers;
GO

