SET NOCOUNT ON;

-- Configuration
DECLARE @SourceDB NVARCHAR(128) = 'WIWA_DB_NEW';
DECLARE @TargetDB NVARCHAR(128) = 'WIWA_Questionnaires_DB';

-- Output Header
SELECT 'USE [' + @TargetDB + '];'
SELECT 'GO'
SELECT 'SET NOCOUNT ON;'
SELECT 'GO'
SELECT '-- Data Migration Script generated by Antigravity'
SELECT ''

-- Ordered List of Tables
DECLARE @Tables TABLE (ID INT IDENTITY(1,1), Name NVARCHAR(128))
INSERT INTO @Tables (Name) VALUES
('QuestionnaireIdentificatorTypes'),
('QuestionnaireTypes'),
('SpecificQuestionTypes'),
('QuestionFormats'),
('ComputeMethods'),
('Ranks'),
('RiskLevels'),
('QuestionnaireIdentificators'),
('Questions'),
('PredefinedAnswers'),
('PredefinedAnswerSubQuestions'),
('QuestionComputedConfigs'),
('Indicators'),
('QuestionnaireTypeRules'),
('QuestionnaireTypeReferenceTables'),
('QuestionReferenceColumns'),
('ProductQuestionaryTypes'),
('QuestionnaireByQuestionnaireIdentificators'),
('Questionnaires'),
('QuestionnaireAnswers');

DECLARE @CurrentID INT = 1;
DECLARE @MaxID INT = (SELECT MAX(ID) FROM @Tables);
DECLARE @TableName NVARCHAR(128);

WHILE @CurrentID <= @MaxID
BEGIN
    SELECT @TableName = Name FROM @Tables WHERE ID = @CurrentID;

    SELECT 'IF OBJECT_ID(''tempdb..#Map_' + @TableName + ''') IS NOT NULL DROP TABLE #Map_' + @TableName + ';';
    SELECT 'CREATE TABLE #Map_' + @TableName + ' (OldID INT, NewID INT);'
    
    DECLARE @ColName NVARCHAR(128);
    DECLARE @IsIdentity BIT;
    DECLARE @RefTable NVARCHAR(128);
    DECLARE @PKName NVARCHAR(128);

    -- Get PK
    SELECT TOP 1 @PKName = c.name 
    FROM sys.indexes i
    INNER JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
    INNER JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
    INNER JOIN sys.tables t ON t.object_id = c.object_id
    WHERE t.name = @TableName AND i.is_primary_key = 1;

    -- Using comma-prepend strategy to allow STUFF removal later
    DECLARE @InsertColList NVARCHAR(MAX) = '';
    DECLARE @ValuesColList NVARCHAR(MAX) = '';
    DECLARE @SelectList NVARCHAR(MAX) = '';
    DECLARE @JoinList NVARCHAR(MAX) = '';

    DECLARE col_cursor CURSOR FOR
        SELECT c.name, c.is_identity, fk_obj.name
        FROM sys.columns c
        INNER JOIN sys.tables t ON t.object_id = c.object_id
        LEFT JOIN (
            SELECT fkc.parent_column_id, fkc.parent_object_id, t_ref.name
            FROM sys.foreign_key_columns fkc
            INNER JOIN sys.tables t_ref ON fkc.referenced_object_id = t_ref.object_id
        ) fk_obj ON fk_obj.parent_column_id = c.column_id AND fk_obj.parent_object_id = c.object_id
        WHERE t.name = @TableName
        ORDER BY c.column_id;

    OPEN col_cursor;
    FETCH NEXT FROM col_cursor INTO @ColName, @IsIdentity, @RefTable;

    DECLARE @SelfRefColumn NVARCHAR(128) = NULL;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- SKIP IDENTITY *AND* PK (to force new ID generation)
        IF (@ColName = @PKName)
        BEGIN
             -- Skip adding to insert list
             PRINT ''; 
        END
        ELSE
        BEGIN
            IF @RefTable = @TableName
            BEGIN
                SET @InsertColList = @InsertColList + ', [' + @ColName + ']';
                SET @ValuesColList = @ValuesColList + ', NULL'; 
                SET @SelectList = @SelectList + ', NULL AS [' + @ColName + ']'; 
                SET @SelfRefColumn = @ColName; 
            END
            ELSE IF @RefTable IS NOT NULL AND @RefTable IN (SELECT Name FROM @Tables)
            BEGIN
                SET @InsertColList = @InsertColList + ', [' + @ColName + ']';
                SET @ValuesColList = @ValuesColList + ', SourceData.[' + @ColName + ']';
                SET @SelectList = @SelectList + ', Map_' + @ColName + '.NewID AS [' + @ColName + ']';
                SET @JoinList = @JoinList + ' LEFT JOIN #Map_' + @RefTable + ' Map_' + @ColName + ' ON Source.[' + @ColName + '] = Map_' + @ColName + '.OldID' + CHAR(13) + CHAR(10);
            END
            ELSE
            BEGIN
                SET @InsertColList = @InsertColList + ', [' + @ColName + ']';
                SET @ValuesColList = @ValuesColList + ', SourceData.[' + @ColName + ']';
                SET @SelectList = @SelectList + ', Source.[' + @ColName + ']';
            END
        END

        FETCH NEXT FROM col_cursor INTO @ColName, @IsIdentity, @RefTable;
    END
    CLOSE col_cursor;
    DEALLOCATE col_cursor;

    -- Remove leading comma
    IF LEN(@InsertColList) > 0 
    BEGIN
        SET @InsertColList = STUFF(@InsertColList, 1, 2, '');
        SET @ValuesColList = STUFF(@ValuesColList, 1, 2, '');
        SET @SelectList = STUFF(@SelectList, 1, 2, '');

        SELECT 'PRINT ''Migrating ' + @TableName + '...'';';
        SELECT 'MERGE INTO [' + @TableName + '] AS Target';
        SELECT 'USING (';
        SELECT '    SELECT ' + @SelectList + ', Source.[' + @PKName + '] AS OldID_Source';
        SELECT '    FROM [' + @SourceDB + '].[dbo].[' + @TableName + '] Source';
        SELECT @JoinList; 
        SELECT ') AS SourceData';
        SELECT 'ON 1 = 0';
        SELECT 'WHEN NOT MATCHED THEN';
        SELECT '    INSERT (' + @InsertColList + ')';
        SELECT '    VALUES (' + @ValuesColList + ')';
        SELECT '    OUTPUT SourceData.OldID_Source, Inserted.[' + @PKName + '] INTO #Map_' + @TableName + ';';
        SELECT 'GO';

        IF @SelfRefColumn IS NOT NULL
        BEGIN
            SELECT 'UPDATE Target';
            SELECT 'SET [' + @SelfRefColumn + '] = Map.NewID';
            SELECT 'FROM [' + @TableName + '] Target';
            SELECT 'INNER JOIN #Map_' + @TableName + ' CurrentMap ON Target.[' + @PKName + '] = CurrentMap.NewID';
            SELECT 'INNER JOIN [' + @SourceDB + '].[dbo].[' + @TableName + '] Source ON CurrentMap.OldID = Source.[' + @PKName + ']';
            SELECT 'INNER JOIN #Map_' + @TableName + ' Map ON Source.[' + @SelfRefColumn + '] = Map.OldID;';
            SELECT 'GO';
        END
    END

    SELECT ''; 
    SET @CurrentID = @CurrentID + 1;
END
